export default {
  ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
  LOAD_CATEGORIES_SUCCESS: 'LOAD_CATEGORIES_SUCCESS',
  UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORIES_SUCCESS',
  DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_TOKEN: 'userToken',
  FAILED_ACTION: 'FAILED_ACTION',
  USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS',
  USER_AUTH_FAILED: 'USER_AUTH_FAILED',
};
